name = "sms-crm-web"
compatibility_date = "2024-01-01"

# Cloudflare Pages configuration
pages_build_output_dir = "out"

# Custom domain for production
[env.production]
domains = ["sms.theprofitplatform.com.au"]

# Environment variables will be set in Cloudflare dashboard

[env.preview]
# Environment variables for preview