name = "sms-crm-web"
compatibility_date = "2024-01-01"

[env.production]
# Environment variables will be set in Cloudflare dashboard

[env.staging]
# Environment variables for staging

# For Pages deployment, this file is optional but can be used for configuration